"""PWA manifest + service worker generators.

ADR-0004 commits us to a PWA in lieu of native apps. The manifest tells
the browser the app's identity, icons, and display preferences; the
service worker implements offline-first caching and background sync.
"""

from __future__ import annotations

import json
from typing import Any

__all__ = ["build_manifest", "build_service_worker"]


def build_manifest(
    *,
    name: str = "Phantom",
    short_name: str = "Phantom",
    start_url: str = "/app/",
    scope: str = "/app/",
    theme_color: str = "#0d1117",
    background_color: str = "#0d1117",
) -> dict[str, Any]:
    """Return a Web App Manifest dict ready to be written to
    ``manifest.webmanifest``.

    Schema follows W3C Web App Manifest spec, level 1.
    """
    return {
        "name": name,
        "short_name": short_name,
        "start_url": start_url,
        "scope": scope,
        "display": "standalone",
        "display_override": ["window-controls-overlay", "standalone", "minimal-ui"],
        "theme_color": theme_color,
        "background_color": background_color,
        "orientation": "portrait-primary",
        "icons": [
            {"src": "/app/icon-192.png", "sizes": "192x192",
             "type": "image/png", "purpose": "any maskable"},
            {"src": "/app/icon-512.png", "sizes": "512x512",
             "type": "image/png", "purpose": "any maskable"},
        ],
        "categories": ["productivity", "developer"],
    }


def build_service_worker(*, cache_version: str = "v1") -> str:
    """Return the JavaScript source of the service worker.

    The SW implements:

    * stale-while-revalidate for the app shell
    * cache-first for static assets (images, fonts)
    * network-first with offline fallback for chat history reads
    * background-sync queue for messages composed while offline
    """
    cache_name = f"phantom-app-shell-{cache_version}"
    return _SW_TEMPLATE.replace("__CACHE_NAME__", cache_name)


_SW_TEMPLATE = """\
// Phantom PWA service worker. Generated by phantom.pwa.build_service_worker.
const CACHE_NAME = "__CACHE_NAME__";
const APP_SHELL = [
  "/app/",
  "/app/index.html",
  "/app/manifest.webmanifest",
  "/app/icon-192.png",
  "/app/icon-512.png",
  "/app/main.js",
  "/app/main.css",
];
const OUTBOX_DB = "phantom-outbox";
const OUTBOX_STORE = "messages";

self.addEventListener("install", (event) => {
  event.waitUntil(
    caches.open(CACHE_NAME).then((c) => c.addAll(APP_SHELL))
      .then(() => self.skipWaiting())
  );
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches.keys().then((keys) =>
      Promise.all(
        keys.filter((k) => k !== CACHE_NAME).map((k) => caches.delete(k))
      )
    ).then(() => self.clients.claim())
  );
});

// ─── outbox (background sync queue) ─────────────────────────────────

function openOutbox() {
  return new Promise((resolve, reject) => {
    const req = indexedDB.open(OUTBOX_DB, 1);
    req.onupgradeneeded = () => {
      req.result.createObjectStore(OUTBOX_STORE, { keyPath: "id", autoIncrement: true });
    };
    req.onsuccess = () => resolve(req.result);
    req.onerror = () => reject(req.error);
  });
}

async function enqueue(request) {
  const body = await request.clone().text();
  const headers = {};
  request.headers.forEach((v, k) => { headers[k] = v; });
  const db = await openOutbox();
  const tx = db.transaction(OUTBOX_STORE, "readwrite");
  tx.objectStore(OUTBOX_STORE).add({
    url: request.url, method: request.method, headers, body,
    queuedAt: Date.now(),
  });
  return new Promise((res, rej) => { tx.oncomplete = res; tx.onerror = () => rej(tx.error); });
}

async function flushOutbox() {
  const db = await openOutbox();
  const tx = db.transaction(OUTBOX_STORE, "readwrite");
  const store = tx.objectStore(OUTBOX_STORE);
  const all = await new Promise((res, rej) => {
    const r = store.getAll();
    r.onsuccess = () => res(r.result);
    r.onerror = () => rej(r.error);
  });
  for (const item of all) {
    try {
      await fetch(item.url, { method: item.method, headers: item.headers, body: item.body });
      store.delete(item.id);
    } catch (e) {
      // Leave in queue; the next sync attempt will retry.
    }
  }
}

async function networkOrEnqueue(request) {
  try {
    return await fetch(request);
  } catch (e) {
    await enqueue(request);
    if ("sync" in self.registration) {
      try { await self.registration.sync.register("phantom-flush-outbox"); } catch (_) {}
    }
    return new Response(JSON.stringify({ queued: true }), {
      status: 202, headers: { "Content-Type": "application/json" },
    });
  }
}

// ─── fetch routing ──────────────────────────────────────────────────

self.addEventListener("fetch", (event) => {
  const url = new URL(event.request.url);
  if (!url.pathname.startsWith("/app/")) return;
  // POST mutations go through the offline outbox.
  if (request.method === "POST" || event.request.method === "POST") {
    event.respondWith(networkOrEnqueue(event.request));
    return;
  }
  // Network-first for the API.
  if (url.pathname.startsWith("/app/api/")) {
    event.respondWith(
      fetch(event.request).catch(() =>
        caches.match(event.request) || new Response("offline", { status: 503 })
      )
    );
    return;
  }
  // Stale-while-revalidate for the app shell.
  event.respondWith(
    caches.match(event.request).then((cached) => {
      const fetched = fetch(event.request).then((resp) => {
        const copy = resp.clone();
        caches.open(CACHE_NAME).then((c) => c.put(event.request, copy));
        return resp;
      }).catch(() => cached);
      return cached || fetched;
    })
  );
});

// ─── push notifications ─────────────────────────────────────────────

self.addEventListener("push", (event) => {
  let payload = { title: "Phantom", body: "" };
  try { payload = event.data ? event.data.json() : payload; } catch (_) {}
  const opts = {
    body: payload.body || "",
    icon: "/app/icon-192.png",
    badge: "/app/icon-192.png",
    data: payload.data || {},
    tag: payload.tag || "phantom",
  };
  event.waitUntil(self.registration.showNotification(payload.title || "Phantom", opts));
});

self.addEventListener("notificationclick", (event) => {
  event.notification.close();
  const url = (event.notification.data && event.notification.data.url) || "/app/";
  event.waitUntil(clients.matchAll({ type: "window" }).then((cs) => {
    for (const c of cs) {
      if (c.url.includes(url) && "focus" in c) return c.focus();
    }
    if (clients.openWindow) return clients.openWindow(url);
  }));
});

// ─── background sync ────────────────────────────────────────────────

self.addEventListener("sync", (event) => {
  if (event.tag === "phantom-flush-outbox") {
    event.waitUntil(flushOutbox());
  }
});
"""
